/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateRecipeIngredientRequest } from './CreateRecipeIngredientRequest';
import {
    CreateRecipeIngredientRequestFromJSON,
    CreateRecipeIngredientRequestFromJSONTyped,
    CreateRecipeIngredientRequestToJSON,
    CreateRecipeIngredientRequestToJSONTyped,
} from './CreateRecipeIngredientRequest';

/**
 * 
 * @export
 * @interface CreateRecipeRequest
 */
export interface CreateRecipeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<CreateRecipeIngredientRequest>}
     * @memberof CreateRecipeRequest
     */
    ingredients?: Array<CreateRecipeIngredientRequest> | null;
}

/**
 * Check if a given object implements the CreateRecipeRequest interface.
 */
export function instanceOfCreateRecipeRequest(value: object): value is CreateRecipeRequest {
    return true;
}

export function CreateRecipeRequestFromJSON(json: any): CreateRecipeRequest {
    return CreateRecipeRequestFromJSONTyped(json, false);
}

export function CreateRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'ingredients': json['ingredients'] == null ? undefined : ((json['ingredients'] as Array<any>).map(CreateRecipeIngredientRequestFromJSON)),
    };
}

  export function CreateRecipeRequestToJSON(json: any): CreateRecipeRequest {
      return CreateRecipeRequestToJSONTyped(json, false);
  }

  export function CreateRecipeRequestToJSONTyped(value?: CreateRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'ingredients': value['ingredients'] == null ? undefined : ((value['ingredients'] as Array<any>).map(CreateRecipeIngredientRequestToJSON)),
    };
}

