/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientResponse } from './IngredientResponse';
import {
    IngredientResponseFromJSON,
    IngredientResponseFromJSONTyped,
    IngredientResponseToJSON,
    IngredientResponseToJSONTyped,
} from './IngredientResponse';

/**
 * 
 * @export
 * @interface IngredientResponsePaginated
 */
export interface IngredientResponsePaginated {
    /**
     * 
     * @type {Array<IngredientResponse>}
     * @memberof IngredientResponsePaginated
     */
    items?: Array<IngredientResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientResponsePaginated
     */
    readonly totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientResponsePaginated
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientResponsePaginated
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientResponsePaginated
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientResponsePaginated
     */
    readonly hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientResponsePaginated
     */
    readonly hasNextPage?: boolean;
}

/**
 * Check if a given object implements the IngredientResponsePaginated interface.
 */
export function instanceOfIngredientResponsePaginated(value: object): value is IngredientResponsePaginated {
    return true;
}

export function IngredientResponsePaginatedFromJSON(json: any): IngredientResponsePaginated {
    return IngredientResponsePaginatedFromJSONTyped(json, false);
}

export function IngredientResponsePaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientResponsePaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(IngredientResponseFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

  export function IngredientResponsePaginatedToJSON(json: any): IngredientResponsePaginated {
      return IngredientResponsePaginatedToJSONTyped(json, false);
  }

  export function IngredientResponsePaginatedToJSONTyped(value?: Omit<IngredientResponsePaginated, 'totalCount'|'totalPages'|'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(IngredientResponseToJSON)),
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
    };
}

