/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum IngredientUnit {
    Grams = 'Grams',
    Milligrams = 'Milligrams',
    Kilograms = 'Kilograms',
    Milliliters = 'Milliliters',
    Liters = 'Liters',
    Pieces = 'Pieces',
    Tablespoons = 'Tablespoons',
    Teaspoons = 'Teaspoons',
    Cups = 'Cups'
}


export function instanceOfIngredientUnit(value: any): boolean {
    for (const key in IngredientUnit) {
        if (Object.prototype.hasOwnProperty.call(IngredientUnit, key)) {
            if (IngredientUnit[key as keyof typeof IngredientUnit] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IngredientUnitFromJSON(json: any): IngredientUnit {
    return IngredientUnitFromJSONTyped(json, false);
}

export function IngredientUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientUnit {
    return json as IngredientUnit;
}

export function IngredientUnitToJSON(value?: IngredientUnit | null): any {
    return value as any;
}

export function IngredientUnitToJSONTyped(value: any, ignoreDiscriminator: boolean): IngredientUnit {
    return value as IngredientUnit;
}

