/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientResponse } from './IngredientResponse';
import {
    IngredientResponseFromJSON,
    IngredientResponseFromJSONTyped,
    IngredientResponseToJSON,
    IngredientResponseToJSONTyped,
} from './IngredientResponse';

/**
 * 
 * @export
 * @interface RecipeIngredientSummary
 */
export interface RecipeIngredientSummary {
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientSummary
     */
    id?: string;
    /**
     * 
     * @type {IngredientResponse}
     * @memberof RecipeIngredientSummary
     */
    ingredient?: IngredientResponse;
    /**
     * 
     * @type {string}
     * @memberof RecipeIngredientSummary
     */
    quantity?: string | null;
}

/**
 * Check if a given object implements the RecipeIngredientSummary interface.
 */
export function instanceOfRecipeIngredientSummary(value: object): value is RecipeIngredientSummary {
    return true;
}

export function RecipeIngredientSummaryFromJSON(json: any): RecipeIngredientSummary {
    return RecipeIngredientSummaryFromJSONTyped(json, false);
}

export function RecipeIngredientSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeIngredientSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ingredient': json['ingredient'] == null ? undefined : IngredientResponseFromJSON(json['ingredient']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

  export function RecipeIngredientSummaryToJSON(json: any): RecipeIngredientSummary {
      return RecipeIngredientSummaryToJSONTyped(json, false);
  }

  export function RecipeIngredientSummaryToJSONTyped(value?: RecipeIngredientSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ingredient': IngredientResponseToJSON(value['ingredient']),
        'quantity': value['quantity'],
    };
}

