/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeSummary } from './RecipeSummary';
import {
    RecipeSummaryFromJSON,
    RecipeSummaryFromJSONTyped,
    RecipeSummaryToJSON,
    RecipeSummaryToJSONTyped,
} from './RecipeSummary';

/**
 * 
 * @export
 * @interface RecipeSummaryPaginated
 */
export interface RecipeSummaryPaginated {
    /**
     * 
     * @type {Array<RecipeSummary>}
     * @memberof RecipeSummaryPaginated
     */
    items?: Array<RecipeSummary> | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeSummaryPaginated
     */
    readonly totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeSummaryPaginated
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeSummaryPaginated
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeSummaryPaginated
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeSummaryPaginated
     */
    readonly hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeSummaryPaginated
     */
    readonly hasNextPage?: boolean;
}

/**
 * Check if a given object implements the RecipeSummaryPaginated interface.
 */
export function instanceOfRecipeSummaryPaginated(value: object): value is RecipeSummaryPaginated {
    return true;
}

export function RecipeSummaryPaginatedFromJSON(json: any): RecipeSummaryPaginated {
    return RecipeSummaryPaginatedFromJSONTyped(json, false);
}

export function RecipeSummaryPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeSummaryPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(RecipeSummaryFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

  export function RecipeSummaryPaginatedToJSON(json: any): RecipeSummaryPaginated {
      return RecipeSummaryPaginatedToJSONTyped(json, false);
  }

  export function RecipeSummaryPaginatedToJSONTyped(value?: Omit<RecipeSummaryPaginated, 'totalCount'|'totalPages'|'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(RecipeSummaryToJSON)),
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
    };
}

