/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeSummary
 */
export interface RecipeSummary {
    /**
     * 
     * @type {string}
     * @memberof RecipeSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeSummary
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeSummary
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeSummary
     */
    imageId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeSummary
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RecipeSummary
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecipeSummary
     */
    lastModified?: Date;
}

/**
 * Check if a given object implements the RecipeSummary interface.
 */
export function instanceOfRecipeSummary(value: object): value is RecipeSummary {
    return true;
}

export function RecipeSummaryFromJSON(json: any): RecipeSummary {
    return RecipeSummaryFromJSONTyped(json, false);
}

export function RecipeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
    };
}

  export function RecipeSummaryToJSON(json: any): RecipeSummary {
      return RecipeSummaryToJSONTyped(json, false);
  }

  export function RecipeSummaryToJSONTyped(value?: RecipeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'imageId': value['imageId'],
        'deleted': value['deleted'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
    };
}

