/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeIngredientSummary } from './RecipeIngredientSummary';
import {
    RecipeIngredientSummaryFromJSON,
    RecipeIngredientSummaryFromJSONTyped,
    RecipeIngredientSummaryToJSON,
    RecipeIngredientSummaryToJSONTyped,
} from './RecipeIngredientSummary';

/**
 * 
 * @export
 * @interface RecipeResponse
 */
export interface RecipeResponse {
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    imageId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeResponse
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RecipeResponse
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecipeResponse
     */
    lastModified?: Date;
    /**
     * 
     * @type {Array<RecipeIngredientSummary>}
     * @memberof RecipeResponse
     */
    ingredients?: Array<RecipeIngredientSummary> | null;
}

/**
 * Check if a given object implements the RecipeResponse interface.
 */
export function instanceOfRecipeResponse(value: object): value is RecipeResponse {
    return true;
}

export function RecipeResponseFromJSON(json: any): RecipeResponse {
    return RecipeResponseFromJSONTyped(json, false);
}

export function RecipeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
        'ingredients': json['ingredients'] == null ? undefined : ((json['ingredients'] as Array<any>).map(RecipeIngredientSummaryFromJSON)),
    };
}

  export function RecipeResponseToJSON(json: any): RecipeResponse {
      return RecipeResponseToJSONTyped(json, false);
  }

  export function RecipeResponseToJSONTyped(value?: RecipeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'imageId': value['imageId'],
        'deleted': value['deleted'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
        'ingredients': value['ingredients'] == null ? undefined : ((value['ingredients'] as Array<any>).map(RecipeIngredientSummaryToJSON)),
    };
}

