/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceSummary
 */
export interface ResourceSummary {
    /**
     * 
     * @type {string}
     * @memberof ResourceSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceSummary
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceSummary
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResourceSummary
     */
    contentType?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceSummary
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ResourceSummary
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ResourceSummary
     */
    lastModified?: Date;
}

/**
 * Check if a given object implements the ResourceSummary interface.
 */
export function instanceOfResourceSummary(value: object): value is ResourceSummary {
    return true;
}

export function ResourceSummaryFromJSON(json: any): ResourceSummary {
    return ResourceSummaryFromJSONTyped(json, false);
}

export function ResourceSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
    };
}

  export function ResourceSummaryToJSON(json: any): ResourceSummary {
      return ResourceSummaryToJSONTyped(json, false);
  }

  export function ResourceSummaryToJSONTyped(value?: ResourceSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'path': value['path'],
        'contentType': value['contentType'],
        'deleted': value['deleted'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
    };
}

