/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceSummary } from './ResourceSummary';
import {
    ResourceSummaryFromJSON,
    ResourceSummaryFromJSONTyped,
    ResourceSummaryToJSON,
    ResourceSummaryToJSONTyped,
} from './ResourceSummary';

/**
 * 
 * @export
 * @interface ResourceSummaryPaginated
 */
export interface ResourceSummaryPaginated {
    /**
     * 
     * @type {Array<ResourceSummary>}
     * @memberof ResourceSummaryPaginated
     */
    items?: Array<ResourceSummary> | null;
    /**
     * 
     * @type {number}
     * @memberof ResourceSummaryPaginated
     */
    readonly totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceSummaryPaginated
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceSummaryPaginated
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceSummaryPaginated
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceSummaryPaginated
     */
    readonly hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceSummaryPaginated
     */
    readonly hasNextPage?: boolean;
}

/**
 * Check if a given object implements the ResourceSummaryPaginated interface.
 */
export function instanceOfResourceSummaryPaginated(value: object): value is ResourceSummaryPaginated {
    return true;
}

export function ResourceSummaryPaginatedFromJSON(json: any): ResourceSummaryPaginated {
    return ResourceSummaryPaginatedFromJSONTyped(json, false);
}

export function ResourceSummaryPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceSummaryPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ResourceSummaryFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

  export function ResourceSummaryPaginatedToJSON(json: any): ResourceSummaryPaginated {
      return ResourceSummaryPaginatedToJSONTyped(json, false);
  }

  export function ResourceSummaryPaginatedToJSONTyped(value?: Omit<ResourceSummaryPaginated, 'totalCount'|'totalPages'|'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ResourceSummaryToJSON)),
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
    };
}

