/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientUnit } from './IngredientUnit';
import {
    IngredientUnitFromJSON,
    IngredientUnitFromJSONTyped,
    IngredientUnitToJSON,
    IngredientUnitToJSONTyped,
} from './IngredientUnit';

/**
 * 
 * @export
 * @interface UpdateIngredientRequest
 */
export interface UpdateIngredientRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateIngredientRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateIngredientRequest
     */
    description?: string | null;
    /**
     * 
     * @type {IngredientUnit}
     * @memberof UpdateIngredientRequest
     */
    unit?: IngredientUnit;
}



/**
 * Check if a given object implements the UpdateIngredientRequest interface.
 */
export function instanceOfUpdateIngredientRequest(value: object): value is UpdateIngredientRequest {
    return true;
}

export function UpdateIngredientRequestFromJSON(json: any): UpdateIngredientRequest {
    return UpdateIngredientRequestFromJSONTyped(json, false);
}

export function UpdateIngredientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIngredientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'unit': json['unit'] == null ? undefined : IngredientUnitFromJSON(json['unit']),
    };
}

  export function UpdateIngredientRequestToJSON(json: any): UpdateIngredientRequest {
      return UpdateIngredientRequestToJSONTyped(json, false);
  }

  export function UpdateIngredientRequestToJSONTyped(value?: UpdateIngredientRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'unit': IngredientUnitToJSON(value['unit']),
    };
}

