/* tslint:disable */
/* eslint-disable */
/**
 * Recipes.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRecipeRequest
 */
export interface UpdateRecipeRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRecipeRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecipeRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UpdateRecipeRequest interface.
 */
export function instanceOfUpdateRecipeRequest(value: object): value is UpdateRecipeRequest {
    return true;
}

export function UpdateRecipeRequestFromJSON(json: any): UpdateRecipeRequest {
    return UpdateRecipeRequestFromJSONTyped(json, false);
}

export function UpdateRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

  export function UpdateRecipeRequestToJSON(json: any): UpdateRecipeRequest {
      return UpdateRecipeRequestToJSONTyped(json, false);
  }

  export function UpdateRecipeRequestToJSONTyped(value?: UpdateRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

